/**
 * Meta keywords (EN / RU / UA) for discoverability. Used in root layout metadata.
 */
export const SITE_KEYWORDS: string[] = [
  // Brand and site name (EN / translit / RU / UA)
  'Zoobastiks',
  'zoobastiks',
  'Zoobastik',
  'zoobastik',
  'Zubastiks',
  'zubastiks',
  'Zubastik',
  'zubastik',
  'zuobastik',
  'Zoobastiks RGB',
  'zoobastiks minecraft',
  'zoobastik text generator',
  'zoobastik.me',
  'zoobastik me zrgb',
  'Зубастик',
  'зубастик',
  'Зубастик генератор',
  'зубастик генератор',
  'Зубастик генератор текста',
  'зубастик генератор текста',
  'Зубастик RGB',
  'зубастик rgb',
  'Зубастик ргб текст',
  'зубастик ргб текст',
  'зубастик майнкрафт',
  'сайт Зубастика',
  'зубастик сайт',
  'Зубастік',
  'зубастік',
  'Zoobastiks генератор',
  'зубастик для майна',
  'зубастик плагины текст',
  // EN and international gamer queries
  'Minecraft RGB',
  'Minecraft RGB generator',
  'Minecraft gradient text',
  'Minecraft rainbow text',
  'MiniMessage gradient',
  'MiniMessage color',
  'Adventure API text',
  'Minecraft color codes',
  'Minecraft hex colors',
  'legacy color codes',
  'ampersand color codes',
  'Minecraft chat formatting',
  'Minecraft plugin text',
  'Minecraft server motd',
  'Minecraft item name color',
  'Minecraft lore color',
  'Minecraft &x RGB',
  'section sign colors',
  'Minecraft JSON text component',
  'Minecraft BBCode colors',
  'Birdflop style gradient',
  'YAML Minecraft editor',
  'Minecraft enchantment IDs',
  'Minecraft effect IDs',
  'Java Edition commands',
  'Minecraft copy paste colors',
  'LuckPerms message',
  'PlaceholderAPI gradient',
  'mc rgb gen',
  'mc gradient generator',
  'how to rgb text minecraft',
  'colored nick minecraft',
  'minecraft gradient nick',
  'make minecraft chat colorful',
  'mc server colored motd',
  'paper spigot gradient text',
  'velocity mini message color',
  // RU formal and adult-style queries
  'Minecraft RGB генератор',
  'генератор градиента Minecraft',
  'градиент текста Minecraft',
  'радужный текст Minecraft',
  'цветной текст Minecraft',
  'коды цветов Minecraft',
  'MiniMessage градиент',
  'форматирование чата Minecraft',
  'название предмета цвет',
  'описание предмета цвет',
  'плагины Minecraft текст',
  'зачарования Minecraft список ID',
  'таблица зачарований Minecraft',
  'эффекты Minecraft ID',
  'список эффектов Minecraft',
  'YAML Minecraft редактор',
  'редактор YAML плагин',
  'копировать цветной текст',
  'RGB для плагинов',
  'инструмент для цветного текста Minecraft',
  'генератор кодов оформления чата',
  'цветные символы для описания предмета',
  'настройка сообщений сервера Minecraft',
  'текст для hologram плагина',
  // RU youth and casual search phrasing
  'ргб генератор майнкрафт',
  'ргб текст майн',
  'ргб ник майнкрафт',
  'как сделать градиент в майне',
  'как покрасить текст в майнкрафте',
  'как цветной текст в чате майн',
  'градиент ника майн',
  'цветной ник генератор',
  'генератор цветного ника',
  'крч ргб текст майн',
  'типа градиент майнкрафт',
  'чат цветной майн сервер',
  'майн ргб копировать',
  'майнкрафт градиент бесплатно',
  'плагин текст цветной онлайн',
  'юзать генератор ргб',
  'залить цветной текст в конфиг',
  'шмот цветное название майн',
  'лор цветной minecraft',
  'мини месседж градиент русский',
  // RU mixed keyboard and typos (how people type)
  'minecraft rgb generator',
  'gradient text maincraft',
  'mine craft rgb',
  'майнкрафт ргб генератор',
  'майнкрафт градиент текста',
  'зубастикс',
  'зубастикс генератор',
  // UA formal
  'Minecraft RGB генератор',
  'генератор градієнта Minecraft',
  'градієнт тексту Minecraft',
  'кольорові коди Minecraft',
  'форматування чату Minecraft',
  'зачарування Minecraft ID',
  'таблиця зачарувань Minecraft',
  'ефекти Minecraft ID',
  'список ефектів Minecraft',
  'редактор YAML Minecraft',
  'копіювати кольоровий текст',
  'RGB для плагінів',
  'інструмент для кольорового тексту Minecraft',
  'коди кольору для чату сервера',
  // UA casual and youth-style
  'як зробити градієнт в майні',
  'кольоровий нік майнкрафт',
  'градієнт тексту для чату',
  'зубастик генератор тексту',
  'зубастик ргб',
  'zoobastiks україна',
  'майн градієнт онлайн',
  'кольоровий текст для плагіна',
]

export const ENCHANT_KEYWORDS: string[] = [
  'Zoobastiks enchant list',
  'зубастик зачарования',
  'zoobastik enchant id',
  'Minecraft enchantment list',
  'Minecraft enchantment registry id',
  'Java enchantment max level',
  'список зачарований Minecraft',
  'ID зачаровань Minecraft',
  'список зачарувань Minecraft',
  'рівень зачарування max',
  'все зачарования майнкрафт таблица',
  'зачарования для команд копировать',
  'enchant id list java',
]

export const EFFECTS_KEYWORDS: string[] = [
  'Zoobastiks effects',
  'зубастик эффекты',
  'zoobastik effect id',
  'Minecraft status effect id',
  'Minecraft potion effect command',
  'список эффектов Minecraft',
  'ID эффектов Minecraft',
  'ефекти Minecraft список',
  'статус ефекти Minecraft',
  'все эффекты майнкрафт для команды',
  'effect give список id',
]

export const SERVER_KEYWORDS: string[] = [
  'minecraft server settings',
  'server.properties editor',
  'paper.yml settings',
  'spigot.yml settings',
  'bukkit.yml settings',
  'minecraft server admin panel',
  'настройки сервера minecraft',
  'редактор server.properties',
  'панель администрации майнкрафт',
  'paper global yml',
]
