export type ServerConfigFile =
  | 'server.properties'
  | 'bukkit.yml'
  | 'spigot.yml'
  | 'paper-global.yml'
  | 'paper-world-defaults.yml'

export type SettingType = 'boolean' | 'number' | 'text' | 'select'

export type ServerSetting = {
  id: string
  file: ServerConfigFile
  keyPath: string
  label: string
  description: string
  type: SettingType
  value: string | number | boolean
  options?: string[]
}

export const SERVER_SETTINGS: ServerSetting[] = [
  {
    id: 'motd',
    file: 'server.properties',
    keyPath: 'motd',
    label: 'MOTD сервера',
    description: 'Текст, который игрок видит в списке серверов.',
    type: 'text',
    value: 'A Minecraft Server',
  },
  {
    id: 'max-players',
    file: 'server.properties',
    keyPath: 'max-players',
    label: 'Максимум игроков',
    description: 'Лимит одновременно подключенных игроков.',
    type: 'number',
    value: 99,
  },
  {
    id: 'online-mode',
    file: 'server.properties',
    keyPath: 'online-mode',
    label: 'Онлайн-режим',
    description: 'Проверка лицензии Mojang. Для публичных серверов обычно true.',
    type: 'boolean',
    value: false,
  },
  {
    id: 'difficulty',
    file: 'server.properties',
    keyPath: 'difficulty',
    label: 'Сложность',
    description: 'Глобальная сложность мира.',
    type: 'select',
    value: 'hard',
    options: ['peaceful', 'easy', 'normal', 'hard'],
  },
  {
    id: 'pvp',
    file: 'server.properties',
    keyPath: 'pvp',
    label: 'PVP',
    description: 'Разрешить урон между игроками.',
    type: 'boolean',
    value: true,
  },
  {
    id: 'view-distance',
    file: 'server.properties',
    keyPath: 'view-distance',
    label: 'Дальность прорисовки',
    description: 'Сколько чанков сервер отправляет игроку.',
    type: 'number',
    value: 8,
  },
  {
    id: 'simulation-distance',
    file: 'server.properties',
    keyPath: 'simulation-distance',
    label: 'Дальность симуляции',
    description: 'Радиус, где тикают сущности и механизмы.',
    type: 'number',
    value: 4,
  },
  {
    id: 'enable-command-block',
    file: 'server.properties',
    keyPath: 'enable-command-block',
    label: 'Командные блоки',
    description: 'Включает выполнение командных блоков.',
    type: 'boolean',
    value: true,
  },
  {
    id: 'allow-flight',
    file: 'server.properties',
    keyPath: 'allow-flight',
    label: 'Разрешить полет',
    description: 'Отключает кик за полет для игроков/плагинов.',
    type: 'boolean',
    value: true,
  },
  {
    id: 'spawn-protection',
    file: 'server.properties',
    keyPath: 'spawn-protection',
    label: 'Защита спавна',
    description: 'Радиус защиты от изменений блоков на спавне.',
    type: 'number',
    value: 0,
  },
  {
    id: 'server-port',
    file: 'server.properties',
    keyPath: 'server-port',
    label: 'Порт сервера',
    description: 'Порт, на котором слушает Minecraft-сервер.',
    type: 'number',
    value: 20054,
  },
  {
    id: 'enable-rcon',
    file: 'server.properties',
    keyPath: 'enable-rcon',
    label: 'RCON',
    description: 'Удаленное управление сервером. Нужен надежный пароль.',
    type: 'boolean',
    value: true,
  },
  {
    id: 'settings.warn-on-overload',
    file: 'bukkit.yml',
    keyPath: 'settings.warn-on-overload',
    label: 'Предупреждение о перегрузке',
    description: 'Логирует предупреждения при лагах/отставании TPS.',
    type: 'boolean',
    value: true,
  },
  {
    id: 'settings.connection-throttle',
    file: 'bukkit.yml',
    keyPath: 'settings.connection-throttle',
    label: 'Connection throttle',
    description: 'Минимальная пауза между подключениями с одного IP (мс).',
    type: 'number',
    value: 0,
  },
  {
    id: 'spawn-limits.monsters',
    file: 'bukkit.yml',
    keyPath: 'spawn-limits.monsters',
    label: 'Лимит монстров',
    description: 'Базовый лимит монстров для спавна.',
    type: 'number',
    value: 40,
  },
  {
    id: 'ticks-per.monster-spawns',
    file: 'bukkit.yml',
    keyPath: 'ticks-per.monster-spawns',
    label: 'Интервал спавна монстров',
    description: 'Частота попытки спавна монстров (тики).',
    type: 'number',
    value: 4,
  },
  {
    id: 'settings.timeout-time',
    file: 'spigot.yml',
    keyPath: 'settings.timeout-time',
    label: 'Таймаут watchdog',
    description: 'Сколько секунд до аварийного завершения при зависании.',
    type: 'number',
    value: 60,
  },
  {
    id: 'settings.bungeecord',
    file: 'spigot.yml',
    keyPath: 'settings.bungeecord',
    label: 'BungeeCord режим',
    description: 'Включать только при прокси BungeeCord/Waterfall.',
    type: 'boolean',
    value: false,
  },
  {
    id: 'settings.user-cache-size',
    file: 'spigot.yml',
    keyPath: 'settings.user-cache-size',
    label: 'Размер кеша пользователей',
    description: 'Сколько профилей хранить в usercache.',
    type: 'number',
    value: 1000,
  },
  {
    id: 'world-settings.default.mob-spawn-range',
    file: 'spigot.yml',
    keyPath: 'world-settings.default.mob-spawn-range',
    label: 'Радиус спавна мобов',
    description: 'Радиус вокруг игрока для спавна мобов.',
    type: 'number',
    value: 4,
  },
  {
    id: 'world-settings.default.item-despawn-rate',
    file: 'spigot.yml',
    keyPath: 'world-settings.default.item-despawn-rate',
    label: 'Деспавн предметов',
    description: 'Через сколько тиков предметы исчезают.',
    type: 'number',
    value: 6000,
  },
  {
    id: 'chunk-loading-basic.player-max-chunk-load-rate',
    file: 'paper-global.yml',
    keyPath: 'chunk-loading-basic.player-max-chunk-load-rate',
    label: 'Лимит загрузки чанков',
    description: 'Ограничение скорости загрузки чанков на игрока.',
    type: 'number',
    value: 100,
  },
  {
    id: 'proxies.velocity.enabled',
    file: 'paper-global.yml',
    keyPath: 'proxies.velocity.enabled',
    label: 'Velocity proxy',
    description: 'Включается только при использовании прокси Velocity.',
    type: 'boolean',
    value: false,
  },
  {
    id: 'packet-limiter.all-packets.max-packet-rate',
    file: 'paper-global.yml',
    keyPath: 'packet-limiter.all-packets.max-packet-rate',
    label: 'Лимит пакетов',
    description: 'Защита от packet-spam на уровне соединения.',
    type: 'number',
    value: 500,
  },
  {
    id: 'misc.max-joins-per-tick',
    file: 'paper-global.yml',
    keyPath: 'misc.max-joins-per-tick',
    label: 'Подключений за тик',
    description: 'Сглаживает нагрузку при массовом входе игроков.',
    type: 'number',
    value: 5,
  },
  {
    id: 'anticheat.anti-xray.enabled',
    file: 'paper-world-defaults.yml',
    keyPath: 'anticheat.anti-xray.enabled',
    label: 'Anti-Xray',
    description: 'Скрывает руды от Xray-клиентов.',
    type: 'boolean',
    value: false,
  },
  {
    id: 'entities.spawning.per-player-mob-spawns',
    file: 'paper-world-defaults.yml',
    keyPath: 'entities.spawning.per-player-mob-spawns',
    label: 'Per-player mob spawns',
    description: 'Учитывает лимиты спавна персонально для каждого игрока.',
    type: 'boolean',
    value: true,
  },
  {
    id: 'chunks.delay-chunk-unloads-by',
    file: 'paper-world-defaults.yml',
    keyPath: 'chunks.delay-chunk-unloads-by',
    label: 'Задержка выгрузки чанков',
    description: 'Чанк остается в памяти после ухода игроков.',
    type: 'text',
    value: '10s',
  },
  {
    id: 'collisions.max-entity-collisions',
    file: 'paper-world-defaults.yml',
    keyPath: 'collisions.max-entity-collisions',
    label: 'Лимит коллизий сущностей',
    description: 'Снижает нагрузку в местах с большим скоплением мобов.',
    type: 'number',
    value: 4,
  },
  {
    id: 'environment.optimize-explosions',
    file: 'paper-world-defaults.yml',
    keyPath: 'environment.optimize-explosions',
    label: 'Оптимизация взрывов',
    description: 'Снижает нагрузку при массовых взрывах.',
    type: 'boolean',
    value: false,
  },
]

export const CONFIG_FILE_ORDER: ServerConfigFile[] = [
  'server.properties',
  'bukkit.yml',
  'spigot.yml',
  'paper-global.yml',
  'paper-world-defaults.yml',
]

export function fileDisplayName(file: ServerConfigFile): string {
  return file
}
